#include"stdio.h"
#defineN5
intReadDat(inta[N]){
	intx;
printf("请输入%d个四位数:\n",N);
for(x=0;x<N;x++)
{
printf("a[%d]:",x);
scanf("%d",&a[x]);
}
return0;
}
floatjsValue(inta[N]){
inti,j,k,l,x,cnt=0,cnt1=0,sum=0,sum1=0;
floatpjz1,pjz2;
for(x=0;x<N;x++){
i=a[x]/1000;
j=(a[x]%1000)/100;
k=(a[x]%1000%100)/10;
l=a[x]%1000%100%10;
if((i+j)==(k+l)){
cnt=cnt+1;
sum=sum+a[x];}
else{
cnt1=cnt1+1;
sum1=sum1+a[x];}
}
pjz1=sum/cnt;
pjz2=sum1/cnt1;
return0;
}
floatWriteDat(floatpjz1,floatpjz2){
	printf("满足该条件的所有数的平均值为%f\n不满足该条件的所有数的平均值为%f\n",pjz1,pjz2);
	return0;
}
voidmain(){
inta[N];
floatpjz1,pjz2;
ReadDat(a);
jsValue(a);
WriteDat(pjz1,pjz2);
}
